### ISSUE TITLE
Pass scalac flags to the endpoint

### ISSUE THREAD

**Issue by jdesiloniz** [scala-exercises/evaluator#48]
- [x] We need to be able to pass Scala compiler flags to the endpoint, so they'll be added to the ones in use when the code snippets are executed. 
- [x] Update the evaluator client so third-party users can send the compiler flags in a straightforward way.

**Comment by dominv** [comment]
@raulraja I've created a PR https://github.com/scala-exercises/evaluator/pull/49 that adds the ability to send scalac's flag to the endpoint but I've observed that some of the available flags cause an, initially, unexpected response. As an example:

For this request (with an already existing path):
```
{
	"resolvers":["https://oss.sonatype.org/content/repositories/releases"],
	"dependencies":[],
	"code":"{List(1, 3, 5)}",
	"compilerFlags":["-d", "/whatever/path" ]
}
```
I get this response: 
```
{
  "msg": "Runtime Error",
  "value": "None.get",
  "valueType": "java.util.NoSuchElementException",
  "compilationInfos": {}
}
```
Although the compiler has done his job right, according to the `-d` flag.

How should we proceed here? Do we have to control this kind of responses caused by the different flags available?

**Comment by raulraja** [comment]
Can we restrict the passed flags to a subset? Only retain from the request those that we need or want to explicitly support in this round then we can evaluate down the road if we want to open this across the board for all flags. Obviously some of the compiler flags can even have security concerns and I think if we just allow a few for now it'd be better.
